### ISSUE TITLE
image probably broken 

### ISSUE THREAD

**Issue by 97harsh** [sapgan/CS628-Assignments#2]
Error from Virtual Box
Failed to import appliance /home/harsh/Downloads/CS628-Assignments-master/vm-628.ova.

Error reading OVA file '/home/harsh/Downloads/CS628-Assignments-master/vm-628.ova' (VERR_TAR_UNEXPECTED_EOS).

Result Code: VBOX_E_FILE_ERROR (0x80BB0004)
Component: ApplianceWrap
Interface: IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

**Comment by sapgan** [comment]
Did you download the entire file. You need to use git-lfs or you can get it from here  https://mega.nz/#!TwQ31IiS!7A6Yz5xZYUb4m4FuEyRZkDP0m9BXLNWkO6JC-2GBTdk
